
package com.ramz.soap.SOAP;


import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Command", targetNamespace = "http://service.commandj11.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Command {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/createGroupRequest", output = "http://service.commandj11.example.com/Command/createGroupResponse")
    public String createGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/deleteUserFromGroupRequest", output = "http://service.commandj11.example.com/Command/deleteUserFromGroupResponse")
    public String deleteUserFromGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns com.ramz.soap.SOAP.SetOfUser
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getAllUsersAndGroupsRequest", output = "http://service.commandj11.example.com/Command/getAllUsersAndGroupsResponse")
    public SetOfUser getAllUsersAndGroups();

    /**
     * 
     * @return
     *     returns com.ramz.soap.SOAP.SetOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getAllGroupsRequest", output = "http://service.commandj11.example.com/Command/getAllGroupsResponse")
    public SetOfString getAllGroups();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/addUserToGroupRequest", output = "http://service.commandj11.example.com/Command/addUserToGroupResponse")
    public String addUserToGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ramz.soap.SOAP.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getUserRequest", output = "http://service.commandj11.example.com/Command/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns com.ramz.soap.SOAP.SetOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getAllChatIdsRequest", output = "http://service.commandj11.example.com/Command/getAllChatIdsResponse")
    public SetOfString getAllChatIds();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/saveUserRequest", output = "http://service.commandj11.example.com/Command/saveUserResponse")
    public String saveUser(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
