
package com.ramz.soap.SOAP;


import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RouterServiceImpl", targetNamespace = "http://impl.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RouterServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendNotification", targetNamespace = "http://impl.service/", className = "com.ramz.soap.SOAP.SendNotification")
    @ResponseWrapper(localName = "sendNotificationResponse", targetNamespace = "http://impl.service/", className = "com.ramz.soap.SOAP.SendNotificationResponse")
    @Action(input = "http://impl.service/RouterServiceImpl/sendNotificationRequest", output = "http://impl.service/RouterServiceImpl/sendNotificationResponse")
    public String sendNotification(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
