
package com.ramz.soap.SOAP;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RouterServiceImplService", targetNamespace = "http://router/", wsdlLocation = "https://df51-176-32-190-26.eu.ngrok.io/?wsdl")
public class RouterServiceImplService
    extends Service
{

    private final static URL ROUTERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROUTERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ROUTERSERVICEIMPLSERVICE_QNAME = new QName("http://router/", "RouterServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://df51-176-32-190-26.eu.ngrok.io/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROUTERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ROUTERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RouterServiceImplService() {
        super(__getWsdlLocation(), ROUTERSERVICEIMPLSERVICE_QNAME);
    }

    public RouterServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROUTERSERVICEIMPLSERVICE_QNAME, features);
    }

    public RouterServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ROUTERSERVICEIMPLSERVICE_QNAME);
    }

    public RouterServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROUTERSERVICEIMPLSERVICE_QNAME, features);
    }

    public RouterServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RouterServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RouterServiceImpl
     */
    @WebEndpoint(name = "RouterServiceImplPort")
    public RouterServiceImpl getRouterServiceImplPort() {
        return super.getPort(new QName("http://router/", "RouterServiceImplPort"), RouterServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RouterServiceImpl
     */
    @WebEndpoint(name = "RouterServiceImplPort")
    public RouterServiceImpl getRouterServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://router/", "RouterServiceImplPort"), RouterServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROUTERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ROUTERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ROUTERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
